export const TaskActivityAction = {
  TASK_CREATED: "TASK_CREATED",
  TASK_UPDATED: "TASK_UPDATED",
  STATUS_CHANGED: "STATUS_CHANGED",
  PRIORITY_CHANGED: "PRIORITY_CHANGED",
  ASSIGNEE_ADDED: "ASSIGNEE_ADDED",
  ASSIGNEE_REMOVED: "ASSIGNEE_REMOVED",
  COMMENT_ADDED: "COMMENT_ADDED",
  COMMENT_UPDATED: "COMMENT_UPDATED",
  COMMENT_DELETED: "COMMENT_DELETED",
  DUE_DATE_CHANGED: "DUE_DATE_CHANGED",
  TASK_MOVED: "TASK_MOVED",
  TASK_DELETED: "TASK_DELETED",
} as const;

export type TaskActivityActionType =
  (typeof TaskActivityAction)[keyof typeof TaskActivityAction];
